name: "✅ Task"
description: "A specific piece of work."
type: "Task"
title: "✅ Task: "
labels: ["Task", "triage"]
body:
  - type: textarea
    id: scope
    attributes:
      label: "Scope of Work"
      description: "Detailed explanation of what needs to be coded, designed, or resolved."
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: "Technical Details / Assumptions"
      description: "Any relevant business rules, edge cases, or dependencies."
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      placeholder: "- [ ] Condition of satisfaction 1\n- [ ] Condition of satisfaction 2"
    validations:
      required: true
  - type: dropdown
    id: estimated-effort
    attributes:
      label: "Effort"
      options:
        - XS (< 2 hours)
        - S (half day)
        - M (1 day)
        - L (2–3 days)
        - XL (1 week+)
    validations:
      required: true
